# Generated by Django 2.0.5 on 2020-07-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateName', models.CharField(max_length=30)),
                ('CandidateId', models.CharField(max_length=20)),
                ('ContactNum', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
